### ISSUE TITLE
Project merge suggestion

### ISSUE THREAD

**Issue by ikeydoherty** [todorez/tummiboot#2]
Heya @todorez :)

So, given that tummiboot isn't moving atm, and gummiboot is dead, do you mind if I see about rebasing and merging your patches into my fork [1]? 

I think it'd be quite useful.

Cheers, and great work btw!
- ikey

[1] https://github.com/solus-project/goofiboot

**Comment by todorez** [comment]
Hey @ikeydoherty,

How is it going? Long time no speak.. :).  
Sure, feel free to reuse any of the tummiboot patches for goofiboot. 

Take care. Speak soon.

Todor

**Comment by ikeydoherty** [comment]
@todorez good ta, you? On "vacation" atm :D 

I shall pluck away then, thanks! :)

**Comment by todorez** [comment]
All is good here, thanks. Feel free to drop me a direct email if you need help with the patches. 
You know my email address.. :).

Cheers,
Todor

**Comment by ikeydoherty** [comment]
Indeed! Cheers fella, talk in a bit :]
